name: Deployment - Main Branch

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to run
        default: 'general'
        options:
          - general
          - homepage
          - solar
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Linter and Prettier
        run: |
          npx eslint --quiet
          npx prettier --check .
      - name: Run Nightwatch tests
        run: |
          environment=${{ github.event.inputs.environment || 'general' }}
          xvfb-run --auto-servernum npm run test:$environment -- --env chrome
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build allure report and history
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
      - name: Generate compressed allure report
        if: always()
        continue-on-error: true
        run: |
          sudo apt-get install -y zip
          zip -r allure-report.zip allure-report/
      - name: Upload artifact for 10 days
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: allure-report.zip
          retention-days: 10
      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
